config/routes.rb
RorGallery::Application.routes.draw do

  root :to => 'pictures#home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/admin/user_events/:user_id/navigation' => 'admin/user_events#navigation', as: :admin_event_user_navigation
  get '/admin/user_events/:user_id/user_sign_in' => 'admin/user_events#event_sign_in', as: :admin_event_user_sign_in
  get '/admin/user_events/:user_id/user_sign_out' => 'admin/user_events#event_sign_out', as: :admin_event_user_sign_out
  get '/admin/user_events/:user_id/like' => 'admin/user_events#event_like', as: :admin_event_like
  get '/admin/user_events/:user_id/subscribe' => 'admin/user_events#event_subscribe', as: :admin_event_subscribe
  get '/admin/user_events/:user_id/comments' => 'admin/user_events#event_comments', as: :admin_event_comments

  scope '(:locale)', locale: /en|ru/ do
    get '/' => 'pictures#home', as: :locale_root
    get 'categories/:slug/:id' => 'pictures#show', as: :picture

    resources :categories, only: [:index, :show]

    resources :pictures, only: [:index] do
      get ':page', action: :index, on: :collection
    end
    resources :comments, only: [:index] do
      get ':page', action: :index, on: :collection
    end

    devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations'}
  end

  # POST method for ajax
  post 'load_comments' => 'pictures#load_comments'
  post 'comment'=> 'comments#create', as: :comment_create
  post 'like' => 'likes#create'
  post 'dislike' => 'likes#destroy'
  post 'subscribe' => 'categories#subscribe'
  post 'unsubscribe' => 'categories#unsubscribe'
  post '/pusher/auth'

  mount Resque::Server, :at => '/resque'

end

app/views/users_subscription/user_new_picture_inform.html.haml
%table{width: 700, border: 0, cellpadding: 0, cellspacing: 0, align: 'center', style: 'table-layout: fixed; background: #fff; border:1px solid #ccc;'}
  %thead
    %tr{height: 80, style: 'border-bottom: 1px solid #ccc; background-color: #eee;'}
      %th
      %th{align: 'center', width: 550}
        %table{height: 80, border: 0, cellpadding: 0, cellspacing: 0, style: 'margin-top: 10px;'}
          %tr
            %td{style: 'font-size: 16px; font-weight: bold; color:#000;', align: 'center'}
              %span= @user.name
          %tr
            %td{style: 'font-size:14px; color:#555;'}
              %span
                Add new pictures on
              = link_to 'Gallery', root_url(host: Settings.mailer.url_host)
          %tr
      %th
  %tbody
    - @pictures.each do |picture|
      %tr
        %td
          %td
            %table{width: '100%', border: 0, cellpadding: 0, cellspacing: 0, style: 'margin: 10px 0; border: 1px solid #ccc;'}
              %tbody{style: 'background-color: #fafafa;'}
                %tr
                  %td{width: 276, height: 276, align: 'center', style: 'padding: 10px;'}
                    =image_tag picture.image.url(:thumb)
                  %td
                    %table{width: '100%', border: 0, cellpadding: 0, cellspacing: 0, style: 'margin-top: 10px;'}
                      %tbody
                        %tr
                          %td
                            %span You subscribed to category:
                            %span= link_to picture.category.title, locale_category_url(title: picture.category.title, host: Settings.mailer.url_host)
                        %tr
                          %td
                            %span New picture:
                            %span= link_to picture.title, locale_picture_url(title: picture.category.title, id: picture.id, host: Settings.mailer.url_host)
        %td
    %tr
      %td
      %td{style: 'padding: 10px; background-color: #ededed; border-radius: 5px;'}
        %strong Do not miss anything.
        Stay in the know.
        %a{href: root_url(host: Settings.mailer.url_host), style: 'background-color: #2f96b4; text-decoration: none; cursor: pointer; border-radius: 5px; padding: 5px; float: right;'}
          %span{style: 'color: #fff;'}
            Go to site url
      %td
    %tr{height: 10}
      %td{colspan: 3}
    %tr{height: 80, style: 'border-top: 1px solid #ccc; background-color: #eee;'}
      %td
      %td{style: 'font-family: Helvetica, Arial, sans-serif; font-size: 12px;'}
        %div
          Forgot your password?
          %span= link_to 'reset password', new_user_password_url(host: Settings.mailer.url_host)
        %div
          You can
          %span= link_to 'unsubscribe', locale_categories_url(host: Settings.mailer.url_host)
          from these emails
        %div{style: 'text-align: center;'}
          %strong= "RoR Mercury © #{DateTime.now.strftime('%Y')}"
      %td