config/routes.rb
RorGallery::Application.routes.draw do

  root :to => 'pictures#home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/admin/user_events/:user_id/navigation' => 'admin/user_events#navigation', as: :admin_event_user_navigation
  get '/admin/user_events/:user_id/user_sign_in' => 'admin/user_events#event_sign_in', as: :admin_event_user_sign_in
  get '/admin/user_events/:user_id/user_sign_out' => 'admin/user_events#event_sign_out', as: :admin_event_user_sign_out
  get '/admin/user_events/:user_id/like' => 'admin/user_events#event_like', as: :admin_event_like
  get '/admin/user_events/:user_id/subscribe' => 'admin/user_events#event_subscribe', as: :admin_event_subscribe
  get '/admin/user_events/:user_id/comments' => 'admin/user_events#event_comments', as: :admin_event_comments

  scope '(:locale)', locale: /en|ru/ do
    get '/' => 'pictures#home', as: :locale_root
    get 'categories/:slug/:id' => 'pictures#show', as: :picture

    resources :categories, only: [:index, :show]

    resources :pictures, only: [:index] do
      get ':page', action: :index, on: :collection
    end
    resources :comments, only: [:index] do
      get ':page', action: :index, on: :collection
    end

    devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations'}
  end

  # POST method for ajax
  post 'load_comments' => 'pictures#load_comments'
  post 'comment'=> 'comments#create', as: :comment_create
  post 'like' => 'likes#create'
  post 'dislike' => 'likes#destroy'
  post 'subscribe' => 'categories#subscribe'
  post 'unsubscribe' => 'categories#unsubscribe'
  post '/pusher/auth'

  mount Resque::Server, :at => '/resque'

end

app/models/event.rb
class Event < ActiveRecord::Base

  attr_accessible :kind, :kind_id, :user_id

  belongs_to :user

end

app/views/admin/event/_user_events.html.haml
.main_content_wrapper
  - if @users
    .index_as_table
      %table.index_table.index{border: 0, cellpadding: 0, cellspacing: 0}
        %thead
          %tr
            %th
              User email
            %th
              navigation
            %th
              user sign out
            %th
              user sign in
            %th
              likes
            %th
              subscribe
            %th
              comments
        %tbody
          - @users.each_with_index do |user, index|
            %tr{class: "#{index%2 == 0 ? 'odd' : 'even'}"}
              %td
                = user.email
              %td
                = link_to 'navigation', admin_event_user_navigation_path(user.id)
              %td
                = link_to 'user sign in', admin_event_user_sign_in_path(user.id)
              %td
                = link_to 'user sign out', admin_event_user_sign_out_path(user.id)
              %td
                = link_to 'like/dislike', admin_event_like_path(user.id)
              %td
                = link_to 'subscribe/unsubscribe', admin_event_subscribe_path(user.id)
              %td
                = link_to 'comments', admin_event_comments_path(user.id)
    #index_footer
      %nav.pagination
        = paginate @users, window: 2

app/views/admin/event/event_show.html.haml
.main_content_wrapper
  .index_as_table
    %table.index_table.index{border: 0, cellpadding: 0, cellspacing: 0}
      - unless @event.blank?
        %thead
          %tr
            %th
              User
            %th
              Action
            %th
              time
            %th
              date
        %tbody
          - @event.each do |nav|
            %tr
              %td
                = nav.user.email
              %td
                = nav.kind
              %td
                = nav.created_at.strftime('%H:%m')
              %td
                = nav.created_at.strftime('%d/%m/%Y')
  #index_footer
    %nav.pagination
      = paginate @event, window: 3

app/views/admin/event/user_events.html.haml
.main_content_wrapper
  - if @users
    .index_as_table
      %table.index_table.index{border: 0, cellpadding: 0, cellspacing: 0}
        %thead
          %tr
            %th
              User email
            %th
              navigation
            %th
              user sign out
            %th
              user sign in
            %th
              likes
            %th
              subscribe
            %th
              comments
        %tbody
          - @users.each_with_index do |user, index|
            %tr{class: "#{index%2 == 0 ? 'odd' : 'even'}"}
              %td
                = user.email
              %td
                = link_to 'navigation', admin_event_user_navigation_path(user.id)
              %td
                = link_to 'user sign in', admin_event_user_sign_in_path(user.id)
              %td
                = link_to 'user sign out', admin_event_user_sign_out_path(user.id)
              %td
                = link_to 'like/dislike', admin_event_like_path(user.id)
              %td
                = link_to 'subscribe/unsubscribe', admin_event_subscribe_path(user.id)
              %td
                = link_to 'comments', admin_event_comments_path(user.id)
    #index_footer
      %nav.pagination
        = paginate @users, window: 2

app/views/admin/event/user_navigation.html.haml
.main_content_wrapper
  .index_as_table
    %table.index_table.index{border: 0, cellpadding: 0, cellspacing: 0}
      - unless @navigation.blank?
        %thead
          %tr
            %th
              User
            %th
              URL
            %th
              time
            %th
              date
        %tbody
          - @navigation.each do |nav|
            %tr
              %td
                = nav.user.email
              %td
                %a{href: nav.url, target: '_blank'}
                  = nav.url
              %td
                = nav.created_at.strftime('%H:%m')
              %td
                = nav.created_at.strftime('%d/%m/%Y')
  #index_footer
    %nav.pagination
      = paginate @navigation, window: 3