config/routes.rb
RorGallery::Application.routes.draw do

  root :to => 'pictures#home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/admin/user_events/:user_id/navigation' => 'admin/user_events#navigation', as: :admin_event_user_navigation
  get '/admin/user_events/:user_id/user_sign_in' => 'admin/user_events#event_sign_in', as: :admin_event_user_sign_in
  get '/admin/user_events/:user_id/user_sign_out' => 'admin/user_events#event_sign_out', as: :admin_event_user_sign_out
  get '/admin/user_events/:user_id/like' => 'admin/user_events#event_like', as: :admin_event_like
  get '/admin/user_events/:user_id/subscribe' => 'admin/user_events#event_subscribe', as: :admin_event_subscribe
  get '/admin/user_events/:user_id/comments' => 'admin/user_events#event_comments', as: :admin_event_comments

  scope '(:locale)', locale: /en|ru/ do
    get '/' => 'pictures#home', as: :locale_root
    get 'categories/:slug/:id' => 'pictures#show', as: :picture

    resources :categories, only: [:index, :show]

    resources :pictures, only: [:index] do
      get ':page', action: :index, on: :collection
    end
    resources :comments, only: [:index] do
      get ':page', action: :index, on: :collection
    end

    devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations'}
  end

  # POST method for ajax
  post 'load_comments' => 'pictures#load_comments'
  post 'comment'=> 'comments#create', as: :comment_create
  post 'like' => 'likes#create'
  post 'dislike' => 'likes#destroy'
  post 'subscribe' => 'categories#subscribe'
  post 'unsubscribe' => 'categories#unsubscribe'
  post '/pusher/auth'

  mount Resque::Server, :at => '/resque'

end

app/models/category.rb
class Category < ActiveRecord::Base

  extend FriendlyId
  friendly_id :slug

  attr_accessible :slug, :title_locale, :translations
  translates :title_locale

  has_many :included_pictures, class_name: 'Picture', limit: 3, order: 'RANDOM()'
  has_many :pictures, dependent: :destroy
  has_many :category_subscriptions, dependent: :destroy
  has_many :users, through: :category_subscriptions

  validates :slug, presence: true, length: {minimum: 1, maximum: 255}, uniqueness: true

  active_admin_translates :title_locale

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :authenticate_user!, only: [:subscribe, :unsubscribe]

  def index
    @categories = Category.includes(:users, :translations)
  end

  def show
    @category = Category.includes(:users).where('slug = :slug', slug: params[:id]).first
    @pictures = Picture.includes(:category).where('category_id = :id', id: @category.id).page(params[:page])
  end

  def subscribe
    category_subscribe = current_user.category_subscriptions.new(category_id: params[:category_id])
    if category_subscribe.save

      Resque.enqueue(UserEvents,
                     {user_id: current_user.id,
                      kind: 'subscribe',
                      kind_id: category_subscribe.id
                     })

      render nothing: true
    else
      respond_to do |format|
        format.js{render js:"alert('Error');"}
      end
    end

  end

  def unsubscribe

    category_subscribe = CategorySubscription.where('user_id = :user_id AND category_id = :category_id', user_id: current_user.id, category_id: params[:category_id]).first

    if category_subscribe.respond_to?(:destroy)

      category_subscribe.destroy

      Resque.enqueue(UserEvents,
                     {user_id: current_user.id,
                      kind: 'unsubscribe',
                      kind_id: category_subscribe.id
                     })

      render nothing: true
    else
      respond_to do |format|
        format.js{render js:"alert('Error');"}
      end
    end

  end

end

app/views/categories/index.html.haml
- title I18n.t('views.categories.index.page_title')
%h1.text-center= I18n.t('views.categories.index.title')
%ul.nav.nav-tabs.nav-stacked
  - @categories.each do |category|
    %li
      = link_to category_path(category), title: I18n.t('views.categories.index.link_title', category: category.title_locale) do
        %table{width: '100%'}
          %tbody
            %tr
              %td{width: '10%'}
                - if user_signed_in?
                  - if category.users.include? current_user
                    %span.unsubscribe{id: category.id, title: I18n.t('views.categories.index.unsubscribe_title')}
                  - else
                    %span.subscribe{id: category.id, title: I18n.t('views.categories.index.subscribe_title')}
              %td{width: '20%'}
                = "#{category.title_locale} (#{category.pictures_count})"
              %td.sub{align: 'center'}
                -category.included_pictures.each do |pic|
                  = image_tag pic.image.url(:default, download: true), alt: pic.image_file_name
              %td{width: 128}
                - if category.users.include? current_user
                  = image_tag 'subscribe.png', width: 128

app/views/categories/show.html.haml
- title I18n.t('views.categories.show.page_title', category: @category.title_locale)
- if user_signed_in?
  - if @category.users.include? current_user
    .subscribe-image
      = image_tag 'subscribe.png', width: 128
%h1.text-center= I18n.t('views.categories.show.title', category: @category.title_locale)
%div
  #featured
    %ul
      - @pictures.each do |picture|
        %li
          = link_to picture_path(picture, picture.id) do
            %span.bottom-label
              %i.icon-thumbs-up
              = picture.likes_count
              %i.icon-comment
              = picture.comments_count
            = image_tag picture.image.url(:thumb, download: true), alt: picture.image_file_name
          .reflection
            = image_tag picture.image.url(:thumb, download: true), alt: 'slider-img'
            .overlay
  = paginate @pictures, window: 2